### ISSUE TITLE
Edges of posters have a corner line

### ISSUE THREAD

**Issue by AliMickey** [CTalvio/Monochromic#1]
Only posters with bright colored borders have a curved (border definition?) white line around them on the corners. 

![image](https://user-images.githubusercontent.com/60691199/89115980-fe6c8680-d4d1-11ea-8094-25001aadae66.png)

![image](https://user-images.githubusercontent.com/60691199/89115992-23f99000-d4d2-11ea-8af9-8c6fd6c3f552.png)

**Comment by AliMickey** [comment]
note this happens when hovering over them.

**Comment by CTalvio** [comment]
Fixed in e16cacc43a06da506abc2f7f684bc2fb7e3d9eda
