### ISSUE TITLE
Primary images do not show in Android App

### ISSUE THREAD

**Issue by ggogel** [CTalvio/Monochromic#13]
When viewing a show or movie it does only show the title on top but not the primary image (cover) of the element when using the Android app on a smartphone. Is this intended?

**Comment by CTalvio** [comment]
This is intended.

The mobile UI does not show a cover style image, but instead a banner "preview", but uses the backdrop image for this, this means it neither displays a relevant episode preview nor a an actual cover image, in addition it breaks backdrops. This makes no sense, code for an actual cover is missing entirely, even in the html, and there is no backdrop (as that code instead displays the banner).

This theme changes the backdrop back to a backdrop, but cannot modify the underlying code to bring back a cover image, as it does not exist (to my knowledge) in the html loaded for mobile UIs.
