### ISSUE TITLE
Buttons dont get coloured

### ISSUE THREAD

**Issue by olskar** [CTalvio/Monochromic#14]
![image](https://user-images.githubusercontent.com/18314560/103354085-e6158d80-4aaa-11eb-935c-1fcd2050c264.png)

Is there any way to make the buttons and sidebar-hover other colours as well? :)

**Comment by CTalvio** [comment]
You are using just the custom color add-on.
You need to import the actual theme, too.

![image](https://user-images.githubusercontent.com/4365015/103937177-0e4b5f00-5131-11eb-994f-9870614f39e3.png)
