### ISSUE TITLE
Libraries buttons do not match rest of theme.

### ISSUE THREAD

**Issue by AliMickey** [CTalvio/Monochromic#2]
![image](https://user-images.githubusercontent.com/60691199/89116071-2ad4d280-d4d3-11ea-81c5-9a59c47ee897.png)

![image](https://user-images.githubusercontent.com/60691199/89116074-2e685980-d4d3-11ea-8c2b-368a428effda.png)

**Comment by CTalvio** [comment]
Fixed in 1b5038b60f13e8672330b2bd8315494added3be4
