### ISSUE TITLE
font

### ISSUE THREAD

**Issue by rj-d2** [CTalvio/Monochromic#3]
hi

im using this as my css:
@import url('https://ctalvio.github.io/Monochromic/default_style.css');

but my font is different from yours, see screenshot:
![font](https://user-images.githubusercontent.com/20203399/90233730-d9a3d780-de1e-11ea-98e6-f4813cba58f4.jpg)

**Comment by CTalvio** [comment]
Font seems identical.

The difference seems to be DPI. My pictures are taken on a 1440p monitor with 110% sizing set in the browser.

Edit: or hmm. Were they? There is scroll bar on both for the left menu, that isn't there on 1440p as it can fit the whole menu.

Regardless, the actual font is correct. The boldness/sharpness/rendering seems different.
