### ISSUE TITLE
Using theme with Nginx reverse proxy does not work by default

### ISSUE THREAD

**Issue by LickABrick** [CTalvio/Monochromic#4]
When using the Nginx Reverse proxy config from the [Jellyfin docs](https://jellyfin.org/docs/general/networking/nginx.html) the theme will not work by default.

Because the config includes [Content-Security-Policy](https://content-security-policy.com/) which reduces risk of XSS (great they thought about this) you need to add the URL from this repo and the fonts to the list of allowed external sources.

In the nginx config you should change the 
`add_header Content-Security-Policy ....` 
to:
`add_header Content-Security-Policy "default-src https: data: blob:; style-src 'self' 'unsafe-inline' https://ctalvio.github.io/Monochromic/default_style.css https://fonts.googleapis.com/css2; script-src 'self' 'unsafe-inline' https://www.gstatic.com/cv/js/sender/v1/cast_sender.js https://www.youtube.com/iframe_api https://s.ytimg.com https://ctalvio.github.io/Monochromic/default_style.css; worker-src 'self' blob:; connect-src 'self'; object-src 'none'; frame-ancestors 'self'";`

If you don't do this the theme will simply not load (reverts back to default theme) and the browser console will spit out an error.

Even if you paste in the CSS by hand the font will still not load since it is loaded from an external source.

Might be handy to add to the docs ;)

**Comment by CTalvio** [comment]
Looks like this is not a thing when using subpath. Which I am.

Will add for those who are not doing that. Thanks!
