### ISSUE TITLE
There is no manual login button

### ISSUE THREAD

**Issue by Arbitrate3280** [CTalvio/Monochromic#5]
Hello, there is no manual login button on the login page:

![1](https://user-images.githubusercontent.com/26132870/90707539-33b4fa80-e26e-11ea-9ff8-9da06c517ecf.png)
![2](https://user-images.githubusercontent.com/26132870/90707544-37488180-e26e-11ea-8d7f-aa3db96383a5.png)

I don't have my admin account listed on there, so if I want to log in I have to first select another user, and then remove his name and put mine in. 

Is this intended?

**Comment by CTalvio** [comment]
No, but also sorta yes.

I do not display any user icons, so the login is always manual. When I created this tweak there was "manual" button even on that screen, that did nothing. I removed it. Seems Jellyfin has updated the behaviour since.

I have fixed it.
