### ISSUE TITLE
The Top bar does not slide back

### ISSUE THREAD

**Issue by hackmonker** [CTalvio/Monochromic#8]
Maybe it is not a issue just a feature but wanted to make sure

The top bar that says home and favorites does not get pushed back after scrolling down which (atleast for me is distracting I guess). Is it possible to let it slide back like it originally used to? I hope I am clear. Thanks a lot for such an awesome theme btw. loving it.

Also any way to reduce the size of the posters in desktop view? cause it is too large for me also reduce the my media icons? thanks a lot

**Comment by CTalvio** [comment]
This is indeed a feature in JF webUI. But it's contextual. It happens on mobile but not desktop. I haven't broken or messed with it yet. I intend to make some sort of solution for the ugly overlapping of the task bar in the future, but I am still testing. (There is some commented out WIP code in there already.)

Stay tuned.

Changing the sizes of stuff is tedious, as the UI sizes things according to detected display size, meaning you have change the sizing for each detected size window. I have done this, with the cast icons, so it's possible.

Also what poster, specifically, are you referring to? The title page poster is easy to resize, so I could just give you a line of code for that one.

**Comment by hackmonker** [comment]
By posters I meant the latest movies posters in the main page and the posters inside the library. Thanks a lot for such an awesome theme anyway. will stay tuned for future changes. Also can we control the background blur after using import?

**Comment by CTalvio** [comment]
Yes.

`.backdropImage {
  filter: blur(60px) saturate(200%) contrast(160%) brightness(25%);
}`

Add this line after the imports. Changing the numbers will edit the filtering for backdrops. You have to inlcude the other filters as well, as if you only enter the blur value, the others will reset to defaults.

**Comment by hackmonker** [comment]
wow thanks a lot. so the only thing remains is the size of the poster which I assume cant be changed so easily. Do tell in case it is possible at some point. Also sorry for asking these things in a github issue but how to change the library icons to just text tabs instead of images. I saw somewhere so asking. Is it even possible?

**Comment by hackmonker** [comment]
Also How did you make the my media like this?

https://github.com/CTalvio/Monochromic/blob/master/screenshots/6.png

**Comment by CTalvio** [comment]
That is a setting in jellyfin. Go to "profile menu" (top-right user icon) then "Home". Change "My media" to "small".

As I have now implemented a solution for the top bar overlapping the media being scrolled, I'll close the issue.

**Comment by hackmonker** [comment]
Sorry to again open this. But just informing in case you did not know about it. The Top sliding implementation was fine in desktop but in mobile the top came as pitch black instead of following the background color. Hope I was clear. If not do tell and I will post screenshots. thanks a lot.

**Comment by CTalvio** [comment]
That is sadly due to how backdrops work differently on mobile. (In that they don't actually exist on all pages).

The current implementation is actually a bit of a workaround, It shifts around the banner image to become the backdrop, due to this the image is not actually in the "backdrop" container, but in the "page" container. This is a difference in the html code, and hence something I cannot affect. Due to this, the backdrop fades out along with everything else on those pages.

You can use the performance add-on to get the backdrop back in the top bar, due to it using margin to not display the scrolled items, rather than a transparency mask.
