### ISSUE TITLE
Random Overlay of color when using custom accents

### ISSUE THREAD

**Issue by Richiachu** [CTalvio/Monochromic#9]
When using the following in custom CSS:

```
@import url('https://ctalvio.github.io/Monochromic/default_style.css');
@import url('https://ctalvio.github.io/Monochromic/sharp_style.css'); 
@import url('https://ctalvio.github.io/Monochromic/customcolor-advanced_style.css');
:root {--accent: 245, 53, 170;}
```

There's color bleeding over some images in the Continue Watching & Next Up sections of the Home screen
![jellyfin](https://user-images.githubusercontent.com/15695528/94352560-1dad0d80-0056-11eb-94de-3b2584bb4436.jpg)

E: Turns out I'm an idiot and misread what the progress indicator would look like. Thanks for the assistance.

**Comment by hackmonker** [comment]
I think that is the progress bar

**Comment by CTalvio** [comment]
Yes. The progress indicator of this theme is a transparent color overlay. It's visible, using the default white accent in the topmost screenshot in the readme.

You can use the bottom bar style progress add-on if you'd rather it be like the stock indicator.

Edit: The color isn't random. It is the accent color.
